title: Lexi Galantino
author: Lexi Galantino
author_nickname: Lexi
email: public@galantino.pw
description: "<code>human && developer</code>"
baseurl: ""
url: "http://galantino.pw"
twitter_username: galantlex
github_username:  gallexi

# Build settings
markdown: kramdown
kramdown:
  input: GFM # GitHub Flavored Markdown
  hard_wrap: false
plugins:
  - jekyll-feed
theme-color: light

github:
  username: gallexi
  repository_url: https://github.com/gallexi/gallexi.github.io
  branch: master

defaults:
  - scope:
      path: "resume.pdf"
    values:
      layout: page
      title: Resume
      permalink: /resume.pdf
